# Toml: Credit Netlify Docs
[build]
  base = "project/"
  command = "echo 'default context'"

[context.production]
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "8.0.1" }

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 302
  force = true
  query = {id = ":id"}
  conditions = {Language = ["en"], Country = ["US"]}
  signed = "API_SIGNATURE_TOKEN"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"